---
title: "Interactive Intermediate Microeconomics"
author: "Yogi Gohel"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  This is a minimal example of using the bookdown package to write a book.
  set in the _output.yml file.
  The HTML output format for this example is bookdown::bs4_book,
biblio-style: apalike
csl: chicago-fullnote-bibliography.csl
always_allow_html: yes
---

# About {-}

This book is designed to help students develop an intuition for intermediate microeconomic concepts using interactive plots and animations. 

By no means is this a replacement for your course textbook; it should serve as a supplement that builds confidence towards more complex topics.

## Notes {-} 

This book is still a work in progress, so there is a chance you will find typos or inconsistencies. Please let me know if you find any at yogi (dot) gohel (at) rutgers (dot) edu.

All chapters besides Chapter 1, [Consumer Behavior], are placeholders. They will be updated as work on the book proceeds.

## Prerequisites {-}

This book assumes familiarity with topics covered in an introductory microeconomics course and univariate differential calculus; at Rutgers these are 01:220:102 and 01:640:135/151, respectively.

## Usage {-}

While it is not recommended, you can view this book on a smaller device such as a phone. The plots will still be interactive, but they do not properly scale to the smaller screen. For the best reading experience, use a laptop or computer. 
